### ISSUE TITLE
Mantine

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/nextjs-wordpress#26]
I'd like to replace Tailwind and custom components for [Mantine](https://mantine.dev/). 

## Phase 1

- [x] Remove Tailwind, autoprefixer, and postcss packages
- [x] Remove global CSS
- [x] Remove all Tailwind markup in HTML

## Phase 2

- [x] Install Mantine
- [x] Refactor both `app.tsx` and `_document.tsx` to instantiate Mantine
- [x] Replace React Icons with Tabler icons

## Phase 3

- [ ] Replace or refactor custom components and pages to use Mantine components
- [ ] Test all the things

**Comment by leonlafa** [comment]
Could you please assign me to this ticket?

**Comment by leonlafa** [comment]
Have you made a start on this @gregrickaby?    Happy to help.

**Comment by gregrickaby** [comment]
@leonlafa I have. Just haven't pushed my branch yet (but will today). 

If there's anything else you see (either issues or in the codebase itself) feel free to create an issue and tackle it!

**Comment by gregrickaby** [comment]
@leonlafa I've got the initial work up [here](https://github.com/gregrickaby/nextjs-wordpress/pull/35) and Mantine is configured.  

Feel free to jump in and begin work on Phase 3 items!

**Comment by leonlafa** [comment]
>@leonlafa I've got the initial work up [here](https://github.com/gregrickaby/nextjs-wordpress/pull/35) and Mantine is configured.
> 
> Feel free to jump in and begin work on Phase 3 items!

@gregrickaby I'm working on Phase 3 today.  

Would you like me to keep the styling for the nav links as the default Mantine or 
style it the way it was before when we had Tailwind in the app?

For example, Mantine, in their example use the following styling:

https://user-images.githubusercontent.com/44982724/194760593-f43d89e7-829e-4a13-b4af-58421ccca8c9.mov

**Comment by gregrickaby** [comment]
@leonlafa Good morning! 

I'm 100% onboard with using default Mantine components/styling with light tweaks via `createStyles()` here and there. 

You and I are on the same page, because your screencast looks like https://ui.mantine.dev/category/headers#header-menu (which is exactly what I was thinking of using). So far I've got the provider and `<Layout />` component scaffolded. This should clear the way.

I've been pushing to this branch https://github.com/gregrickaby/nextjs-wordpress/tree/feature/%2326-mantine, and now that you're a collaborator (💪🏻 ) you should be able to commit and push to that one too.

While you work on components, I'm going to refactor the `<CommentForm>` to use Mantine's form workflow.

Thanks again for all the help!!!
